# Generated by Django 6.0.6 on 2026-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Short description shown in card view')),
                ('content', models.TextField(blank=True, help_text='Full article content (for articles)')),
                ('category', models.CharField(choices=[('digital_rights', 'Digital Rights'), ('privacy', 'Data Privacy'), ('ai_policy', 'AI Policy'), ('cybersecurity', 'Cybersecurity'), ('internet_governance', 'Internet Governance'), ('general', 'General')], max_length=50)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'PDF'), ('link', 'External Link')], default='article', max_length=20)),
                ('url', models.URLField(blank=True, help_text='External link (for videos, PDFs, links)', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional image/thumbnail URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
