# Generated by Django 6.0.6 on 2026-07-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_quiz_description_alter_quiz_passing_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
