# Generated by Django 6.0.6 on 2026-07-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
